controllers:
    resource: ../src/Controller/
    type: attribute

# hello_world:
#     path: /hello
#     controller: App\Controller\HelloWorld::hello

# home:
#     path: /
#     controller: App\Controller\Home::home